#author Robert Vivar 
#date 2025-04-14
#description Build and Test

name: Build and Test

on:
  pull_request:
    branches: [develop]
    type: [ opened , reopened ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      ##########################################################
      # Download code from feature branch, setup JDK, and cache Maven
      ##########################################################
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
      
    - name: Build with Maven
      run: |
        echo "Java version set up"
        java -version
        echo "Maven version set up"
        mvn --version
        echo "mvn -B clean install --file pom.xml -Dnative=true"
        mvn -B clean install --file pom.xml -Dnative=true

      ##########################################################
      # Automate the build and test process
      ##########################################################

  merge-feature-into-develop:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ success() }}
    permissions:
      contents: write
      pull-requests: write
    steps:
    ############################################################
# 1 - Download code from feature branch, setup JDK, and cache Maven
    ############################################################
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref}}
        fetch-depth: 0
    #############################################################
    # 2- Merge to development branch
    #############################################################
    - name: Merge feature branch into 
      if: ${{ success() }}
      run: |
        git config --local user.email "email-of-workflow@user"
        git config --local user.name "Workflow-user"
        #Using -m "mesage" on merge command ins mandatori
        git merge --no-ff --verbose origin/${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{github.event.number}}"
    ############################################################
    # 3 - Push changes after merge 
    ############################################################
    - name: Push changes after merge
      if: ${{ success() }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.base_ref }}
    