#author Robert Vivar 
#date 2025-04-12
#description Build and Test

name: Build and Test

on:
  push:
    branches: 
    - 'main'
    - feature/*
  pull_request:
    branches: 
    - 'main'
    - feature/*


jobs:
  build-and-test:

    runs-on: ubuntu-latest
    environment: dev
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Build with Maven
      run: |
        echo "Java version set up"
        java -version
        echo "Maven version set up"
        mvn --version
        echo "mvn -B clean install --file pom.xml -Dnative=true"
        mvn -B clean install --file pom.xml -Dnative=true

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}